ERROR: Cannot install -r requirements.txt (line 39) and pillow~=11.1.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested pillow~=11.1.0
    crawl4ai 0.6.3 depends on pillow~=10.4

Additionally, some packages in these conflicts have no matching distributions available for your environment:
    pillow

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts